### ISSUE TITLE
messageformat update

### ISSUE THREAD

**Issue by giacomo** [lephyrus/ngx-translate-messageformat-compiler#91] opened 2022-09-22 10:34 UTC
Which version of 'messageformat' is the last supported version of this plugin?

```
ngx-translate-messageformat-compiler/fesm2020/ngx-translate-messageformat-compiler.mjs depends on 'messageformat'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

Is there any chance of getting rid of the warning message? Without the use of `allowedCommonJsDependencies `?

Angular Version: 14
ngx-translate-messageformat-compiler: latest
messageformat: 2.3.0

**Comment by tuuling** [comment] 2022-09-26 10:58
messageformat npm package is actually depracated and moved to https://www.npmjs.com/package/@messageformat/core Might as well switch it out to the correct one.

**Comment by lephyrus** [comment] 2022-09-26 12:02
Closing as duplicate of #74.

**Closed by lephyrus** 2022-09-26 12:02 UTC
